### ISSUE TITLE
User Story 1: Dog basic data

### ISSUE THREAD

**Issue by RonnySteady** [RonnySteady/dogpass#1]
## Value Proposition

As a User 
I want to see some basic information about my dogs starting with the name
in order to be able to chose the right dog from the list.
​

## Description

![image](https://github.com/RonnySteady/dogpass/assets/130970897/3316b64b-56e4-4acb-86c9-abb1f6fc78d3)

... (Wireframe, scribble, design or text)
​

## Acceptance Criteria

- [ ] Describe every scenario in detail
- [ ] e.g. all inputs are required, show warning if empty.
- [ ] ...
      ​

## Tasks

- [ ] list the coding tasks that need to be performed
- [ ] e.g. create branch `feature/xyz`
- [ ] e.g. Components
- [ ] e.g. Component Tests
- [ ] ...

**Comment by actyvystom** [comment]
Hi Ronald, 
A nice and short one, I like it 😉 
Anyway some comments to consider:
- In your value proposition you talk of a list of dogs - that does not appear in either scribble, acceptance criteria or task list
- You could adjust like so: 
> As a user,
> I want to see a list of my dogs names 
> in order to choose a dog from the list to display further information

You could start this with some dummy dog data and set up a second user story describing how to add a dog (like this one does basically and display the list of already created dog names)

**Comment by FelineHuhn** [comment]
Hey Ronald, nice start! 🎉

I share the opinion of Thomas, that your first user story only could display a list of dogs from a dog mock array, and a second user story could be a feature, to add a new dog. Please adjust your wireframes, acceptance criteria, and tasks accordingly. 

It would be great, if you would use realistic dog names instead of "Name 1" to make your user story more clearly. The save/edit button is not used by now, so that should be removed, or?

Your acceptance criteria for a first user story with only a list of dogs could be something like: 
- [ ] the headline is "Dogs App"
- [ ] dogs are displayed as cards in a list 
- [ ] the dog cards include the dog name

Your tasks could be something like: 
- [ ] create a branch called feature/dogslist
- [ ] create dogs mock array
- [ ] add a headline
- [ ] create a `Dog` component
     - [ ] add name
- [ ] use the `Dog` component to display the dogs mock data

**Comment by RonnySteady** [comment]
Thank you Feline, i adapted your suggestions for criteria and tasks, also added a new wireframe.

**Comment by FelineHuhn** [comment]
Nice job Ronald 🚀
