### ISSUE TITLE
User Story 8: UI optimizations, change App-Name, add favicon.ico

### ISSUE THREAD

**Issue by RonnySteady** [RonnySteady/dogpass#17]
## Value Proposition

**As a** dog owner
**I want to** see the app name and a favicon in the browser tab or window 
**so that/in order to** have a good user experience
​

## Description

![image](https://github.com/RonnySteady/dogpass/assets/130970897/b141fd7f-6e65-46ce-b350-3339351fd5cf)
​

## Acceptance Criteria

- [ ] the app should have a recognition value with a favicon
- [ ] the app should show the name 'Dog Pass' instead of Capstone Project
- [ ] the DogCard and OwnerCard should have a better readability
      ​

## Tasks

- [ ] create a branch feature/favicon-appname
- [ ] add a Favicon.ico the the public folder 
- [ ] change the apps name from 'Capstone Project' to 'Dog Pass'
- [ ] optimize background and font of cards for better readability

**Comment by CarstenJahnke** [comment]
LGTM Ronald ☺️☺️
