### ISSUE TITLE
User Story 2: Add more input fields to the form 

### ISSUE THREAD

**Issue by RonnySteady** [RonnySteady/dogpass#2]
## Value Proposition

**As a User
**I want to add more information about my dogs
**to have an complete overview of my dogs with detailed information
​

## Description

​

## Acceptance Criteria

- [ ] I want to add date of birth, place of birth, breed/race and color
- [ ] input fields should also be empty at first 
- [ ] new input fields should have the same buttons (save/edit) like name field 

## Tasks

- [ ] extend the form with the new input fields
- [ ] e.g. create branch `feature/xyz`
- [ ] e.g. Components
- [ ] e.g. Component Tests
- [ ] ...

**Comment by FelineHuhn** [comment]
Hey Ronald, 
from now on, please post your user stories in the user-stories channel, so that everyone can give you a review. 😊

I have some suggestions for you: I think your user story should better be the adding of a new dog instead of only the add button, since the button has no function without a form to add a dog. Please adjust this to your whole user story and than post it again.

**Comment by FelineHuhn** [comment]
As I see your user story is already in review, but one tiny thing i forgot about: You should give the input label for "Name:" also a * so the user knows, it's also required like the other input fields with a * , or? 😊

**Comment by MariaRiosNavarro** [comment]
LGFM 🚀

**Comment by RonnySteady** [comment]
Thanks Maria!  
Thank you Feline, I just made the labels consistent.
