### ISSUE TITLE
User Story 4: Edit function for DogCard

### ISSUE THREAD

**Issue by RonnySteady** [RonnySteady/dogpass#7]
## Value Proposition

**As a** dog owner
**I want to** edit the data in existing cards and/or add more information to them
**so that** my Dog Pass is always up to date.  
​

## Description

![image](https://github.com/RonnySteady/dogpass/assets/130970897/da108714-217b-4172-a3c3-73cfbae91b90)​

## Acceptance Criteria

- [ ] there should be a small edit button with pen symbol to edit the `DogCard`
- [ ] after click on the `edit` button the `DogCard` is in edit mode, where I can change the information 
- [ ] in edit mode there should be a `save` button to update the information 
- [ ] after click on the `save` button the user gets redirected to the page with the `DogList` component that shows the updated card
​

## Tasks

- [ ] create a feature branch called feature/edit-function
- [ ] add an `edit` button on the `DogCard` component
- [ ] add logic for the `edit` button to invoke the edit mode of the `DogCard`
- [ ] add a `save` button to the card in edit mode to save the data
- [ ] add logic for the `save` button to redirect the user back to the `DogList` after editing a `DogCard`

**Comment by actyvystom** [comment]
Really nice one! 🚀 
But please adjust your value proposition as it is describing your delete functionality... 😉 
Cheers, Thomas
