### ISSUE TITLE
User Story 5: New page with OwnerCard

### ISSUE THREAD

**Issue by RonnySteady** [RonnySteady/dogpass#9]
## Value Proposition

**As a** dog owner
**I want to** save my personal data in the app
**so that** I can forward this data, e.g. to the vet
​

## Description

... (Wireframe, scribble, design or text)
​

## Acceptance Criteria

- [ ] the personal data of the owner should be displayed in a separate routable page /owner 
- [ ] inputs are not required, the user can decide on his own, how much information the user wants to share

      ​

## Tasks

- [ ] create a new feature branch feature/ownercard
- [ ] e.g. create branch `feature/xyz`
- [ ] e.g. Components
- [ ] e.g. Component Tests
- [ ] ...

**Comment by rueveydaakuel** [comment]
In my opinion it is very well written and easy to understand.
I have nothing to complain about. LGTM 👍
